#!/usr/bin/env bash
set -eu -o pipefail

die() {
    echo 1>&2 "$(basename "$0"):" "$@";
    exit 1;
}

base=$(cd "$(dirname "$0")" && pwd -P)
cd $base

. ./activate
#pytest -q "$@"

sudo -v || die 'Cannot sudo to run docker'
py="sudo $base/.build/virtualenv/bin/python3"

#   We always build a test image; it's tagged :latest by hand.
image=capps-bind:test

#pytest -q "$@"

server=$($py capps-named.py)
record=$($py test_client.py $server)

[[ $record == *"thisisatextrecord"* ]] || \
die "FAIL: named did not return expected DNS records, instead received $record"

echo OK
